# Configs
num_workers: 64
base_dir: /home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/
pretrained_path: pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar
data:
  class_mapping: pretrained_models/class_mapping.txt
  species_mapping: pretrained_models/species_id_to_name.txt
  train_data: /home/rtcalumby/adam/luciano/PlantCLEF2025/images_max_side_800/
  output_dir: /home/rtcalumby/adam/luciano/PlantCLEF2025/cached_features/
